name: 'terraform fmt'
description: 'Runs `terraform fmt` and comments on a PR with reviewdog.'

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/exec/wrapper-terraform-fmt.sh
      shell: bash
